### ISSUE TITLE
Please add a submenu for imgur upload

### ISSUE THREAD

**Issue by AdrienLemaire** [Toqozz/slip#3]
Would be great if I could use slip for everything, including

- Taking a screenshot without uploading it to imgur
- Taking a video and uploading it to imgur

Instead of showing a notification on completion, can you display the rofi menu to answer the question "Do you want to upload to imgur?" ?

To upload videos, we can convert them into gif images:
```
$ mplayer -ao null vid-2017-05-29-155452.mkv -vo jpeg:outdir=vid-2017-05-29-155452/
$ ffmpeg -i vid-2017-05-29-155452/00000%03d.jpg vid-2017-05-29-155452.gif
$ imgur.sh vid-2017-05-29-155452.gif
```

Thanks for considering this feature

EDIT: forgot about imgur's nginx filesize limitation. Might be worth considering another hosting service for videos.

**Comment by Toqozz** [comment]
I've recently also run into situations where I don't want to upload to imgur, and have been considering adding the option not to upload.  However, I can't think of a particularly appealing way to achieve this that works for everyone.  For me, another box popping up a few seconds later would be annoying, and if anything I'd rather just select "screenshot (no upload)" in the first place.  I suppose that I could turn the prompt on and off with a config option, I'll think a bit more about it.

As for the gifs/videos... I've also considered adding this to slip before, because gifs are really 10x more useful in showing a quick video than uploading to youtube.  The problem I found while quickly looking into it in the past was that I'd have to string together a number of commands to get it to work, however that command you show in your post seems easy enough (I suspect you can also use ffmpeg to generate the frames for the video).
Imgur says the limit for uploading non-static content is [200mb](https://help.imgur.com/hc/en-us/articles/115000083326-What-files-can-I-upload-), but that really doesn't sound right.  I wouln't like to switch away from imgur, so I'd like to find a solution that works with imgur.

Any ideas?

**Comment by AdrienLemaire** [comment]
200MB ? :open_mouth:  I'm pretty sure I failed to upload an ~50MB gif the other day, but... would have to verify. Otherwise, you could auto-compress the resulting gif if it gets too heavy (for example using imagemagick convert with `-fuzz 10% -layers Optimize`, or `-quality 80%`, or `-resize <half dimensions found from identify>` ...)

Showing more options in the first menu with `(no upload)` sounds good too :)
:+1:  for searching a way to generate frames without adding mplayer as new dependency.

I'm looking forward to see the next version :grinning:

**Comment by Toqozz** [comment]
Hey! I've added some basic gif support in da41c78.  Please try it out if you have the chance and let me know of any bugs.

Some things to note:
- Gifs scale horizontally to GIF_SIZE (width in pixels) in the config, while maintaining aspect ratio.
    -  This means that for gifs of a smaller width than GIF_SIZE, they will actually be scaled up!  Which is probably not what you want.  I'll fix this in time.
- The previous point also means that their filesize grows much more quickly with height rather than width.
- Imgur won't let me upload with slip past 10mb, I believe the 200mb limit is for account holders.
    - Could maybe add OAuth support, but I think that this is outside slips complexity.
    - You'll be prompted with an upload option if the filesize is under 10mb.

If you have any ideas regarding the scaling, I'd like to hear them.  My current plan is to have GIF_SCALEW and GIF_SCALEH in the config, and decide whichever is best for the situation when the time comes.

I haven't added the support for not uploading yet, sorry!  I was thinking of having the "no upload" as a command line option, as in, maybe you would run slip with `slip --noupload` when you don't want to upload an image (assuming most of the time you do want to upload).

PS: ffmpeg can actually record directly to gif, so that was good :)

**Comment by AdrienLemaire** [comment]
Thank @Toqozz, that was fast!

When I'm trying it, there's quite a loss of  image quality though. Wondering if it's only a problem in my local system...

![](http://i.imgur.com/jcJMG67.gif)

Your code lgtm, so it must have to do with ffmpeg arguments..

**Comment by Toqozz** [comment]
Hmm... are you referring to the color ?  I’m not exactly sure what causes this, but I will take a look.

**Comment by Toqozz** [comment]
Gifs are limited to 256 colors it seems.  By default ffmpeg uses a color palette that covers a wide range of colors, but they might not be very accurate.  I think this is the main problem with the colors.  

You can avoid this by creating a palette, but to my understanding it requires creating a video and then a palette based on that video and then converting the video to a gif using that palette.

My main problem with this is that I’d prefer to avoid juggling files, particularly in bash, but when I get time I’ll take a look!

**Comment by Toqozz** [comment]
The quality should be a bit better now:
![Gif quality sample.](http://i.imgur.com/RCyinSy.gif)

You can find the newer version on the 'dev' branch (I should be using branches more).  As before, please try it out and let me know of anything you want changed etc.  The code is a bit messy, I'll try clean it up before pushing it to the master branch/aur when the time comes.

**Comment by Toqozz** [comment]
Merged to main branch / aur.

Closing this but haven't forgotten about screenshotting without uploading.

**Comment by AdrienLemaire** [comment]
Sorry, didn't have time to test this out more. Thanks for the work !
