### ISSUE TITLE
Allow slip --stop

### ISSUE THREAD

**Issue by NolanSyKinsley** [Toqozz/slip#4]
It is sorta useless to have a gif recorder if the end of the gif recording you see running slip again and manually selecting stop. Please allow the command slip --stop to stop recording and save the file, without asking if it should be deleted.

**edit** looking through the code I see slip -q will stop recording. Please either put this in the readme, along with the rest of the options you omitted or at least make slip --stop synonymous with slip -q. One should not have to dig into the code to find simple functions like these that should be documented in the readme on github.

As it is a script I did not expect --help to work, which such a feature should also be listed on the github readme.

**Comment by Toqozz** [comment]
Not as useless as you might think!  Typically only a small selection of the desktop needs to be cut out to make a gif.  Unless your rofi display covers the whole screen, usually it can be out of the way.

But I do understand the problem, and I'll work on this :).

Do you not want it to ask to be deleted because it may interfere with the recording, or if you just prefer it that way?

**Comment by Toqozz** [comment]
Sorry, just saw your edit.  I thought I had something in place for this...

You're right, the documentation is lacking.  I've updated it.
