### ISSUE TITLE
Give a config option to allow users to upload to their own imgur account.

### ISSUE THREAD

**Issue by NolanSyKinsley** [Toqozz/slip#5]
Check out  how https://github.com/jomo/imgur-screenshot does their configs to allow people to upload images anonymously, or optionally allow them to upload to their personal imgur account.

My hope is to pretty much replicate their script but with gifs, and slip is SOO close! Essentially I want a script that I hit a hotkey, select the area, or click on a window, and it records a gif of that selection or window. It should stop on the next keyboard or mouse input and automatically upload the gif, either to gifycat or imgur, and return the link, copying it to the clipboard. If the gif is too large, it should say so and offer to open the location in the user's file manager.

**Comment by Toqozz** [comment]
I worry that stopping on the next input may be troublesome for most people, where they want to record some action on their PC and that would really get in the way.

I've wanted to add this feature, thanks for giving a source on it!  I'll work on adding optional accounts as soon as I get time.

Would your hope be fulfilled with account support + a way to stop recording without showing slip?  Or are you looking for a way to automatically upload as well (so no "interaction")?

**Comment by Toqozz** [comment]
Hey!  I've added some basic support for this.

The setup process is much simpler than imgur-screenshot, but the tokens expire after 28 days, so you have to renew them (this can be automated quite easily).

I'm really just testing this method out right now.  Since adding an account doesn't actually change upload limits or anything like that, it's hard to find much value in committing a lot to this.

Imgur currently doesn't let applications refresh tokens without the client secret, which can't easily be hidden in this kind of program.  This means that for users to have indefinite uploading to their own account, they have to jump through some hoops registering an application on Imgur's API and figuring out key information.

There's also a little bit more work on the backend for this kind of process, so it would be convenient if I could avoid it :).


Please let me know of any alternate solution you may know of, or if/why you think that jumping through those hoops is worthwhile!
